name: build-and-push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "17 9 * * 1"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  UPSTREAM_IMAGE: stashapp/stash:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Resolve upstream digest
        id: upstream
        shell: bash
        run: |
          set -euo pipefail
          DIGEST="$(docker buildx imagetools inspect "${UPSTREAM_IMAGE}" --format '{{.Manifest.Digest}}')"
          echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"
          echo "Upstream digest: ${DIGEST}"

      # 用上游 digest 作为 cache key：命中则表示“已处理过这个上游版本”
      - name: Restore digest cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .upstream-digest-cache
          key: upstream-${{ steps.upstream.outputs.digest }}

      - name: Skip scheduled build if upstream unchanged
        if: github.event_name == 'schedule' && steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "Upstream unchanged (cache hit); skipping scheduled build."
          exit 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # build 成功后保存 cache（把一个小文件写进 path 即可）
      - name: Write marker file
        run: |
          mkdir -p .upstream-digest-cache
          echo "${{ steps.upstream.outputs.digest }}" > .upstream-digest-cache/digest.txt

      - name: Save digest cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .upstream-digest-cache
          key: upstream-${{ steps.upstream.outputs.digest }}
